language: ruby

before_script:
  - bundle exec rake db:{create,schema:load} RAILS_ENV=test

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - yarn

script:
  - bundle exec rails webpacker:compile
  - bundle exec rspec
